### ISSUE TITLE
License of this repo

### ISSUE THREAD

**Issue by fewwwww** [Winszheng/A-Supplychain-based-on-FISCO-BCOS#1]
你好作者，
我刚开始学习联盟链的开发，想请问这个仓库的开源协议是什么？
还有感觉课程作业做这么完整的一个区块链应用特别强，同时也感觉你的大学能开区块链相关的课程特别厉害，想请问一下你是在哪个大学就读？

**Comment by Winszheng** [comment]
开源协议已加入
中山大学
这个是初学的时候写的，其实没什么技术含量，感谢您的issue

**Comment by fewwwww** [comment]
明白了，谢谢回复！
